### ISSUE TITLE
Add notebook to validate spatial averaging

### ISSUE THREAD

**Issue by tomvothecoder** [xCDAT/xcdat-validation#23]
Validation Checklist
1. API usage (and plots where helpful)
2. Performance metrics (use timeit)
3. Bugs, improvements
4. Questions

Compare below APIs against CDAT equivalent.

* `ds.xcdat.spatial_average()` or `ds.spatial.avg()`

**Comment by pochedls** [comment]
> 1. I think I understand that the spatial average should be conducted on dataset (as in cell [19] of the [notebook](https://github.com/XCDAT/xcdat_test/blob/spatial_avg_tutorial/tutorials/demo_spatial_avg.ipynb)), not data array (which I hoped for doing such as in cell [17] and [18] of the [notebook](https://github.com/XCDAT/xcdat_test/blob/spatial_avg_tutorial/tutorials/demo_spatial_avg.ipynb)). I was hopping for the later case because the data array is a generated one (land masking applied to the given data array of the dataset). Maybe a workaround to be define a new dataset by using the new data array, then apply spatial average to the new dataset?

Yes - you can create a new masked dataset and then call the spatial averager. 

> 2. I think cdms assigns weighting for spatial average as a default while xcdat does not. Should we consider providing default weightings in xcdat for spatial averaging?

xcdat - weights data (by area) by default

**Comment by tomvothecoder** [comment]
> I think cdms assigns weighting for spatial average as a default while xcdat does not. Should we consider providing default weightings in xcdat for spatial averaging?

>xcdat - weights data (by area) by default [Note - I now see the confusion; if you do not pass in a weighting matrix (i.e., default None), then it will calculate the spatial weights for you].

To avoid confusion, we can either rename the method param from `weights` to `custom_weights`, or set the default value to `weights="generate"` instead of `None`.

I'm lean towards `custom_weights=None` because it is clearer that the weights are user-specified (with a tradeoff in verbosity). I'm open to other opinions though.

**Comment by tomvothecoder** [comment]
> To avoid confusion, we can either rename the method param from weights to custom_weights (or some other clearer name), or set the default value to weights="generate" instead of None.

Issue opened to address this: https://github.com/XCDAT/xcdat/issues/147

**Comment by tomvothecoder** [comment]
This issue is from almost 3 years ago and does not need to be addressed anymore.
